version: '3.7'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/node_modules'
    ports:
      - 8080:8080
      - 8081:8081
#    environment:
#      - CHOKIDAR_USEPOLLING=true